name: Continous Integration

on: pull_request

jobs: 
  continous-integration:
  runs-on: unbuntu-latest
  steps:
    - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      name: run install, build and test
      run: |
      npm instal
      npm run build
      npm run test
